In [4]:
import numpy as np

a = [0, 1, 2, 3]

b = np.insert(a, 0, 100)

print(b)

[100   0   1   2   3]


In [5]:
def f(x):
    return x ** 2

def g(x):
    return x ** 3

func = np.array([f, g])

print(func)

[<function f at 0x000001B78D1268C0> <function g at 0x000001B78D2B45E0>]


In [6]:
print(func[0](3))

9


In [37]:
a = [[] for i in range(4)]
a[0].append(f)
a[0][0](3)

9

In [38]:
obstacle_list = [(10, -1, 2), (20, 1, 2)]

In [39]:
obstacle_list[1][0]

20

In [46]:
def a(x):
    return x ** 2

In [47]:
a = a(3)

In [48]:
print(a)

9


In [86]:
import scipy.optimize as optimize
import numpy as np

In [118]:
def func(x):
    sum = 0
    for i in range(2):
        sum += x[i]**2
    return sum

def func1(x):
    return np.cos(x[0])

x0 = [1, 0]

def f(x):
    return -np.cos(x[0]) ** 2 - np.sin(x[1]) ** 2 + 1


constraints = [{'type': 'ineq', 'fun': f}]

bounds = [(None, None), (None, None)]

result = optimize.minimize(func1, x0, method='SLSQP', constraints=constraints)



In [119]:
result

     fun: -0.9999996232241314
     jac: array([0.00086808, 0.        ])
 message: 'Optimization terminated successfully'
    nfev: 36
     nit: 12
    njev: 12
  status: 0
 success: True
       x: array([ 3.14246073e+00, -3.12275491e-09])

In [70]:
functions = {}

for i in range(5):
    def f(x):
        return x ** i
    functions['f'+str(i)] = f
    


In [72]:
print(functions['f0'](2)) # 1
print(functions['f1'](2)) # 2
print(functions['f2'](2)) # 4
print(functions['f3'](2)) # 8
print(functions['f4'](2)) # 16

16
16
16
16
16


In [81]:
# 関数名を自動生成するためのヘルパー関数
def generate_function_name(i):
    return f"function_{i}"
global a
a = [500, 300, 100]
# 100個以上の関数を自動生成する
for i in range(100):
    function_name = generate_function_name(i)
    function_definition = f"def {function_name}(x): return x + a[1] + {i}"
    exec(function_definition)

In [82]:
# 定義した関数を使用する
print(function_0(1))   # 1
print(function_1(1))   # 2
print(function_99(1))  # 100

301
302
400


In [83]:
functions = []

# 関数名を自動生成するためのヘルパー関数
def generate_function_name(i):
    return f"function_{i}"

# 100個以上の関数を自動生成する
for i in range(100):
    function_name = generate_function_name(i)
    function_definition = f"def {function_name}(x): return x + {i}"
    exec(function_definition)
    functions.append(eval(function_name))

# 定義した関数を使用する
print(functions[0](1))   # 1
print(functions[1](1))   # 2
print(functions[99](1))  # 100

1
2
100


In [84]:
functions

[<function __main__.function_0(x)>,
 <function __main__.function_1(x)>,
 <function __main__.function_2(x)>,
 <function __main__.function_3(x)>,
 <function __main__.function_4(x)>,
 <function __main__.function_5(x)>,
 <function __main__.function_6(x)>,
 <function __main__.function_7(x)>,
 <function __main__.function_8(x)>,
 <function __main__.function_9(x)>,
 <function __main__.function_10(x)>,
 <function __main__.function_11(x)>,
 <function __main__.function_12(x)>,
 <function __main__.function_13(x)>,
 <function __main__.function_14(x)>,
 <function __main__.function_15(x)>,
 <function __main__.function_16(x)>,
 <function __main__.function_17(x)>,
 <function __main__.function_18(x)>,
 <function __main__.function_19(x)>,
 <function __main__.function_20(x)>,
 <function __main__.function_21(x)>,
 <function __main__.function_22(x)>,
 <function __main__.function_23(x)>,
 <function __main__.function_24(x)>,
 <function __main__.function_25(x)>,
 <function __main__.function_26(x)>,
 <function 

In [6]:
import numpy as np

def test(x):
    ans = np.array([0, 0, 0])
    for i in range(len(x)):
        ans[i] = x[i] ** 2
    return ans

test(np.array([1, 2, 3]))

array([1, 4, 9])

In [12]:
ans = [1, 2, [3, 4, 5]]
ans[1]


2

In [11]:
ans = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
ans[0, :]

array([0, 0, 0])

In [28]:
import numpy as np
from scipy.optimize import minimize

# 目的関数（最小化対象の関数）
def objective_function(x):
    return x[0]**2 + x[1]**2

# 制約関数
def constraint_function(x, *args):
    return args[0] * x[0] + args[1][0] * x[1] + args[1][1]

# 初期値
x0 = np.array([0.5, 0.5])

# 制約関数に渡す引数
constraint_args = {'a': 2, 'b': -1}

# 制約定義
constraints = [{'type': 'eq', 'fun': constraint_function, 'args': [2, [1, 3]]}]

# 最適化を実行
result = minimize(objective_function, x0, constraints=constraints)

print("Optimal solution:")
print(result.x)  # 最適解の表示
print("Optimal value:")
print(result.fun)  # 最適値の表示

Optimal solution:
[-1.2 -0.6]
Optimal value:
1.8000000000000003


In [25]:
ans = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
ans[0, 0] = 100
ans

array([[100,   0,   0],
       [  1,   1,   1],
       [  2,   2,   2]])